# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daic < Formula
  desc "Chat with documentation and OpenAPI specifications using AI"
  homepage "https://github.com/albertilagan/docs-ai-chat"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/albertilagan/docs-ai-chat/releases/download/v0.0.2/docs-ai-chat_Darwin_x86_64.tar.gz"
      sha256 "cff67e9d285b839bb2f71ef27e5926f41ee05bda5a15871513220828b7893fba"

      def install
        bin.install "daic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/albertilagan/docs-ai-chat/releases/download/v0.0.2/docs-ai-chat_Darwin_arm64.tar.gz"
      sha256 "14ae16eae90cbc2e77e3227fdfc3776c679fb534fae19ac91452be78a96e494a"

      def install
        bin.install "daic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/albertilagan/docs-ai-chat/releases/download/v0.0.2/docs-ai-chat_Linux_x86_64.tar.gz"
        sha256 "0156c67e6bb1c1f90928b7cd1747ae2ec589759111ccf1050d326e20f25dc715"

        def install
          bin.install "daic"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/albertilagan/docs-ai-chat/releases/download/v0.0.2/docs-ai-chat_Linux_arm64.tar.gz"
        sha256 "0d191160aa6a03d700406c15cf8ff9da95e499b423df607f1af18ea354301d4b"

        def install
          bin.install "daic"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Before using daic, set your OpenRouter API key:
        export OPENROUTER_API_KEY="your-api-key"
    EOS
  end

  test do
    system "#{bin}/daic --version"
  end
end
